library(ggplot2)
library(scales)
M<-read.table('/Users/Kallol/Testing/nwa-field1/runs/run1/output/statistics/field1run1discrete1991-2010_1years-statistics_files/field1run1discrete1991-2010_1CollaborationDistribution.csv', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/Field1_Milojevic_1.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Log10(Collaborators)') + ylab('Log10(Number of Authors)') + geom_point(aes(M$Collaborators, M$Frequency)) + geom_line(aes(M$Collaborators, M$Frequency)) + coord_trans(x = "log10", y = "log10")
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)

M<-read.table('/Users/Kallol/Testing/nwa-field2/runs/run1/output/statistics/field2run1discrete1991-2010_1years-statistics_files/field2run1discrete1991-2010_1CollaborationDistribution.csv', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/Field2_Milojevic_1.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Log10(Collaborators)') + ylab('Log10(Number of Authors)') + geom_point(aes(M$Collaborators, M$Frequency)) + geom_line(aes(M$Collaborators, M$Frequency)) + coord_trans(x = "log10", y = "log10")
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)



AB1<-read.table("/Users/Kallol/Testing/nwa-field1/runs/run1/output/statistics/field1run1discrete1991-2010_1years-statistics_files/field1run1discrete1991-2010_1years-AbbasiTable2.csv", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/Field1NewAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of New Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + opts(legend.title=theme_blank())
ggsave(pdffile)

AB1<-read.table("/Users/Kallol/Testing/nwa-field2/runs/run1/output/statistics/field2run1discrete1991-2010_1years-statistics_files/field2run1discrete1991-2010_1years-AbbasiTable2.csv", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/Field2NewAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of New Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + opts(legend.title=theme_blank())
ggsave(pdffile)


AB1<-read.table("/Users/Kallol/Testing/AbbasiTable2.txt", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/AbbasiNewAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of New Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + scale_y_continuous(limits = c(0, 100)) + opts(legend.title=theme_blank())
ggsave(pdffile)

AB1<-read.table("/Users/Kallol/Testing/nwa-field1/runs/run1/output/statistics/field1run1discrete1991-2010_1years-statistics_files/field1run1discrete1991-2010_1years-AbbasiTable2.csv", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/Field1OldAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of old Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + opts(legend.title=theme_blank())
ggsave(pdffile)

AB1<-read.table("/Users/Kallol/Testing/nwa-field2/runs/run1/output/statistics/field2run1discrete1991-2010_1years-statistics_files/field2run1discrete1991-2010_1years-AbbasiTable2.csv", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/Field2OldAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of old Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + opts(legend.title=theme_blank())
ggsave(pdffile)

AB1<-read.table("/Users/Kallol/Testing/AbbasiTable2.txt", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/AbbasiOldAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of old Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + scale_y_continuous(limits = c(0, 40)) +opts(legend.title=theme_blank())
ggsave(pdffile)