library(ggplot2)
library(scales)

#staging starts

M <-read.table('/Users/Kallol/Testing/nwa-field1/runs/run1/output/statistics/field1run1accumulative1991-2010_1years/components/accumulative1991-1991_1years-Large-SecondLargeData.txt', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/SecondEver_1.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Year') + ylab('Percent from Second (ever)') + geom_point(aes(M$End_year, M$Ever_Second_Percent, color = 'From Second')) + geom_line(aes(M$End_year, M$Ever_Second_Percent, color = 'From Second'))+coord_cartesian(ylim=c(0.0, 100.0))
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)

M <-read.table('/Users/Kallol/Testing/nwa-field1/runs/run1/output/statistics/field1run1accumulative1991-2010_1years/components/accumulative1991-1991_1years-Large-SecondLargeData.txt', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/SecondPrevious_1.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Year') + ylab('Percent from Second (just previous)') + geom_point(aes(M$End_year, (M$Just_Previous_Percent), color = 'From Second')) + geom_line(aes(M$End_year, (M$Just_Previous_Percent), color = 'From Second')) + geom_point(aes(M$End_year, M$Percent_from_others, color = 'From Others')) + geom_line(aes(M$End_year, M$Percent_from_others, color = 'From Others'))+geom_point(aes(M$End_year, M$Percent_Previous_Largest, color = 'From Previous Largest')) + geom_line(aes(M$End_year, M$Percent_Previous_Largest, color = 'From Previous Largest')) +geom_point(aes(M$End_year, M$Percent_New, color = 'New Comers')) + geom_line(aes(M$End_year, M$Percent_New, color = 'New Comers')) + coord_cartesian(ylim=c(0.0, 100.0))
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)

M <-read.table('/Users/Kallol/Testing/nwa-field1/runs/run1/output/statistics/field1run1accumulative1991-2010_1years/components/accumulative1991-1991_1years-Large-SecondLargeData.txt', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/SecondPrevious_1_1.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Year') + ylab('Percent from Second (just previous)') + geom_point(aes(M$End_year, (M$Others_Percent), color = 'Other Component')) + geom_line(aes(M$End_year, (M$Others_Percent), color = 'Other Component')) + geom_point(aes(M$End_year, M$Percent_from_others, color = 'From Others')) + geom_line(aes(M$End_year, M$Percent_from_others, color = 'From Others'))+geom_point(aes(M$End_year, M$Percent_Previous_Largest, color = 'From Previous Largest')) + geom_line(aes(M$End_year, M$Percent_Previous_Largest, color = 'From Previous Largest')) +geom_point(aes(M$End_year, M$Percent_New, color = 'New Comers')) + geom_line(aes(M$End_year, M$Percent_New, color = 'New Comers')) + coord_cartesian(ylim=c(0.0, 100.0))
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)

M <-read.table('/Users/Kallol/Testing/nwa-field2/runs/run1/output/statistics/field2run1accumulative1991-2010_1years/components/accumulative1991-1991_1years-Large-SecondLargeData.txt', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/SecondEver_2.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Year') + ylab('Percent from Second (ever)') + geom_point(aes(M$End_year, (M$Ever_Second_Percent))) + geom_line(aes(M$End_year, (M$Ever_Second_Percent))) + coord_cartesian(ylim=c(0.0, 40.0))
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)

M <-read.table('/Users/Kallol/Testing/nwa-field2/runs/run1/output/statistics/field2run1accumulative1991-2010_1years/components/accumulative1991-1991_1years-Large-SecondLargeData.txt', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/SecondPrevious_2.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Year') + ylab('Percent from Second (just previous)') + geom_point(aes(M$End_year, (M$Just_Previous_Percent))) + geom_line(aes(M$End_year, (M$Just_Previous_Percent)))  + coord_cartesian(ylim=c(0.0, 40.0))
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)

#staging ends

M<-read.table('/Users/Kallol/Testing/nwa-field1/runs/run1/output/statistics/field1run1discrete1991-2010_20years/field1run1discrete1991-2010_20HubCollaborationDistribution.csv', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/Field1_HubMilojevic_1.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Log10(Collaborators)') + ylab('Log10(Number of Authors)') + geom_point(aes(M$Collaborators, M$Frequency)) + geom_line(aes(M$Collaborators, M$Frequency)) + coord_trans(x = "log10", y = "log10")
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)

M<-read.table('/Users/Kallol/Testing/nwa-field2/runs/run1/output/statistics/field2run1discrete1991-2010_20years/field2run1discrete1991-2010_20HubCollaborationDistribution.csv', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/Field2_HubMilojevic_1.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Log10(Collaborators)') + ylab('Log10(Number of Authors)') + geom_point(aes(M$Collaborators, M$Frequency)) + geom_line(aes(M$Collaborators, M$Frequency)) + coord_trans(x = "log10", y = "log10")
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)

M<-read.table('/Users/Kallol/Testing/nwa-field1/runs/run1/output/statistics/field1run1discrete1991-2010_1years-statistics_files/field1run1discrete1991-2010_1CollaborationDistribution.csv', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/Field1_Milojevic_1.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Log10(Collaborators)') + ylab('Log10(Number of Authors)') + geom_point(aes(M$Collaborators, M$Frequency)) + geom_line(aes(M$Collaborators, M$Frequency)) + coord_trans(x = "log10", y = "log10")
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)

M<-read.table('/Users/Kallol/Testing/nwa-field2/runs/run1/output/statistics/field2run1discrete1991-2010_1years-statistics_files/field2run1discrete1991-2010_1CollaborationDistribution.csv', header = TRUE, sep = ';')
pdffile <-c("/Users/kallol/Testing/Graphs/Field2_Milojevic_1.pdf")
pdf(pdffile)
p<-ggplot(M)
p + xlab('Log10(Collaborators)') + ylab('Log10(Number of Authors)') + geom_point(aes(M$Collaborators, M$Frequency)) + geom_line(aes(M$Collaborators, M$Frequency)) + coord_trans(x = "log10", y = "log10")
#qplot(log10(Collaborators), log10(Frequency), data = M, geom= c("point", "line"))
ggsave(pdffile)



AB1<-read.table("/Users/Kallol/Testing/nwa-field1/runs/run1/output/statistics/field1run1discrete1991-2010_1years-statistics_files/field1run1discrete1991-2010_1years-AbbasiTable2.csv", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/Field1NewAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of New Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + opts(legend.title=theme_blank())
ggsave(pdffile)

AB1<-read.table("/Users/Kallol/Testing/nwa-field2/runs/run1/output/statistics/field2run1discrete1991-2010_1years-statistics_files/field2run1discrete1991-2010_1years-AbbasiTable2.csv", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/Field2NewAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of New Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + opts(legend.title=theme_blank())
ggsave(pdffile)


AB1<-read.table("/Users/Kallol/Testing/AbbasiTable2.txt", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/AbbasiNewAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of New Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_New_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + scale_y_continuous(limits = c(0, 100)) + opts(legend.title=theme_blank())
ggsave(pdffile)

AB1<-read.table("/Users/Kallol/Testing/nwa-field1/runs/run1/output/statistics/field1run1discrete1991-2010_1years-statistics_files/field1run1discrete1991-2010_1years-AbbasiTable2.csv", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/Field1OldAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of old Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + opts(legend.title=theme_blank())
ggsave(pdffile)

AB1<-read.table("/Users/Kallol/Testing/nwa-field2/runs/run1/output/statistics/field2run1discrete1991-2010_1years-statistics_files/field2run1discrete1991-2010_1years-AbbasiTable2.csv", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/Field2OldAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of old Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + opts(legend.title=theme_blank())
ggsave(pdffile)

AB1<-read.table("/Users/Kallol/Testing/AbbasiTable2.txt", header=TRUE, sep = ';')
p<-ggplot(AB1)
pdffile <-c("/Users/Kallol/Testing/Graphs/AbbasiOldAuthorJoiningComparison.pdf")
pdf(pdffile)
p + xlab('Year') + ylab('Percent of old Authors') + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_point(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_new_author, color = 'With New')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_old_author, color = 'With Old')) + geom_line(aes(AB1$Start_Year,AB1$Percent_Of_Old_Authors_Connected_to_atleast_one_any_author, color = 'With Any')) + scale_y_continuous(limits = c(0, 40)) +opts(legend.title=theme_blank())
ggsave(pdffile)